config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  match "/auth/:provider/callback" => "sessions#create", via: [:get, :post]
  match "/auth/failure", to: "sessions#failure", via: [:get, :post]
  match "/login", to: "sessions#new", :as => "login", via: [:get]
  match "/logout", to: "sessions#destroy", :as => "logout", via: [:get, :post]  #TODO
  match '/register', to: "users#new", :as => "register", via: [:get]
  resources :users do
    member do
      resource :payment_source
    end
  end
  resource  :password
  resource  :password_reset
  resources :auth_tokens
  resources :payments

  resource :demo_result
  resources :users

  post 'address-query' => 'street_address#query', :as => :query_street_address

  get 'health_check' => 'health_check#index', :as => :health_check
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
    render_404 and return if current_user.present?
    render_404 and return unless @user = User.find_by(password_reset_token: params[:t])
  end

  def create
    render_404 and return if current_user.present?
    user = User.find_by(email: params[:email])
    if user
      PasswordReset.new(user).send_password_reset
    else
      flash[:error] = "Sorry, we don't have that email address on file."
      redirect_to new_password_reset_path
    end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/create.html.haml
.row.dialog
  .col-sm-4.col-sm-offset-4
    .well
      %h2.text-center Reset sent.
      %p.text-center Help is on it's way!
      .action.text-center    
        = link_to "Take me home", "/", class: 'btn btn-primary login'

app/views/password_resets/new.html.haml
.row.dialog
  .col-sm-4.col-sm-offset-4
    .well
      %h2.text-center Oopsie!
      %p.text-center Let's reset that password.
      = render partial: 'shared/flash'            
      = form_tag password_reset_path do
        .form-group
          = label_tag :email, "Email"
          = text_field_tag :email, nil, class: 'form-control'
        .action.text-center    
          = submit_tag "Send me a reset e-mail!", class: 'btn btn-primary login'