config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  match "/auth/:provider/callback" => "sessions#create", via: [:get, :post]
  match "/auth/failure", to: "sessions#failure", via: [:get, :post]
  match "/login", to: "sessions#new", :as => "login", via: [:get]
  match "/logout", to: "sessions#destroy", :as => "logout", via: [:get, :post]  #TODO
  match '/register', to: "users#new", :as => "register", via: [:get]
  resources :users do
    member do
      resource :payment_source
    end
  end
  resource  :password
  resource  :password_reset
  resources :auth_tokens
  resources :payments

  resource :demo_result
  resources :users

  post 'address-query' => 'street_address#query', :as => :query_street_address

  get 'health_check' => 'health_check#index', :as => :health_check
end

app/models/user.rb
# from https://gist.github.com/stefanobernardi/3769177
class User < OmniAuth::Identity::Models::ActiveRecord
  include Redis::Objects

  has_many   :identities
  has_many   :payments
  has_many   :daily_usages
  belongs_to :plan, autosave: true

  before_save :update_stripe, :if => Proc.new { |u| u.stripe_token_changed? }
  before_create :assign_default_plan_at_signup
  after_create :add_first_auth_token
  after_commit :send_welcome_email, on: :create
  after_commit :first_recharge

  # TODO
  # email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # validates :email, :presence   => true,
  #           :format     => { :with => email_regex },
  #           :uniqueness => { :case_sensitive => false }
  
  list :auth_tokens
  hash_key :auth_token_descriptions
  value :recharge_threshold

  counter :credits_remaining
  counter :usage_today

  def self.create_with_omniauth(auth)
    # you should handle here different providers data
    # eg. case auth['provider'] ..
    create(name: auth['info']['name'])
    # IMPORTANT: when you're creating a user from a strategy that
    # is not identity, you need to set a password, otherwise it will fail
    # I use: user.password = rand(36**10).to_s(36)
  end

  def has_payment_source?
    self.stripe_token.present?
  end

  def reset_payment_fields
    self.stripe_token = nil
    self.stripe_customer_id = nil
    self.card_last4 = nil
    self.card_exp_year = nil
    self.card_exp_month = nil
    self.card_brand = nil
  end

  def generate_new_token
    SecureRandom.uuid
  end

  protected

  def update_stripe
    PaymentService.sync_with_stripe(user)
  end

  def send_welcome_email
    UserMailer.welcome(self.id).deliver
  end

  def assign_default_plan_at_signup
    self.plan = Plan.default_at_signup.first
  end

  def add_first_auth_token
    uuid = self.generate_new_token
    self.auth_tokens << uuid
    self.auth_token_descriptions[uuid] = ''
  end

  def first_recharge
    RechargeWorker.perform_async(self.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, only: [:show]

  def show
    @payments = current_user.payments.order("created_at DESC").page(params[:page]).per(5)
    @history = DailyUsage.history(current_user)
  end

  def new
    @user = env['omniauth.identity'] ||= User.new
  end

  def update
    if current_user.update_attributes(params.require(:user).permit(:plan_id))
      redirect_to user_path(current_user), notice: "Account settings updated."
    else
      redirect_to user_path(current_user), notice: "Error updating plan: #{current_user.errors.full_messages.to_sentence}"
    end      
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def token_description(user, token)
    current_user.auth_token_descriptions[token].blank? ? 'Default Token' : current_user.auth_token_descriptions[token]
  end
end

app/views/users/_add_token.html.haml
- new_auth_token = current_user.generate_new_token
#addToken.modal.fade
  .modal-dialog
    .modal-content
      = form_tag auth_tokens_path, { class: 'form-horizonal' } do
        .modal-header
          %button{ type: "button", class: "close", data: {dismiss: "modal"} }
            %span
              = fa_icon 'times'
          %h4 Add an API Token
        .modal-body
          .form-group
            = label_tag 'API Token', nil, class: 'control-label col-sm-3'
            .col-sm-9
              %p.form-control-static= new_auth_token
          .form-group
            = label_tag :description, 'Description', class: 'control-label col-sm-3'
            .col-sm-9
              = hidden_field_tag :new_auth_token, new_auth_token 
              = text_field_tag :description, nil, class: 'form-control'
        .modal-footer
          %button{ type: "button", class: "btn btn-default", data: {dismiss: "modal"}} Cancel
          %button{ type: "submit", class: "btn btn-primary" } Save changes

app/views/users/_billing.html.haml
%script{ src: "https://checkout.stripe.com/checkout.js" }

.panel.panel-default
  .panel-heading
    Billing
  .panel-body
    .billing
      - if current_user.has_payment_source?
        %fieldset
          %legend Current card details
          %dl
            %dt Card Number
            %dd **** **** **** #{current_user.card_last4} (#{current_user.card_brand})
            %dt Card Expiration
            %dd #{current_user.card_exp_month} / #{current_user.card_exp_year}
          .card    
            %button#card{ class: 'btn btn-primary' }
              Change credit card
            = link_to "Remove Credit Card", payment_source_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"
      - else  
        You currently do not have a payment source on file. 
        %button#card{ class: 'btn btn-primary' }
          Add a credit card
      %fieldset
        %legend Payment History
        - if current_user.payments.present?
          %table.table.table-condensed
            %thead
              %tr
                %th Date
                %th Description
                %th Amount
                %th Credits
            %tbody#payments
              = render @payments
          #paginator
            = paginate @payments, remote: true, theme: 'bootstrap3'
        - else
          No payments.
          
:coffeescript
  handler = StripeCheckout.configure(
    key: 'pk_test_ueEB0FHAsf8AMIwRkOvBlQE9'
    email: '#{current_user.email}'
    panelLabel: 'Save Payment Source'   
    token: (token,args)->
      $.post(
        '#{payment_source_path}'
        token: token
        (data, textStatus, jqXHR)->
          console.log("success")
        (jqXHR, textStatus, errorThrown)->
          console.log("failed: " + textStatus)
      )
  )

  $('button#card').on 'click', (e)->
    handler.open(
      name: 'Sure Address'
    )
    e.preventDefault()

  $(window).on 'popstate', ()->
    handler.close()

app/views/users/_change_plan.html.haml
#changePlan.modal.fade
  .modal-dialog
    .modal-content
      = form_for current_user, { class: 'form-horizontal', method: :patch } do |f|
        = f.hidden_field :plan_id
        .modal-header
          %button{ type: "button", class: "close", data: {dismiss: "modal"} }
            %span
              = fa_icon 'times'
          %h4 Confirm Recharge Plan Change
        .modal-body
          %p
            Changing to plan:
            %b.new-recharge-plan
          %p
            Your credit card will be charged
            %b.new-recharge-plan-fee
            and
            %b.new-recharge-plan-credits
            credits will be added to your account            
            when your balance drops down to
            %span.new-recharge-plan-threshold
            credits remaining.            
        .modal-footer
          %button{ type: "button", class: "btn btn-default", data: {dismiss: "modal"}} Cancel
          %button{ type: "submit", class: "btn btn-primary" } Change Recharge Plans

:coffeescript
  $('#changePlan').on('show.bs.modal', (e)->
    button = $(e.relatedTarget)
    $('#changePlan input#user_plan_id').val button.data('id')
    $('#changePlan .new-recharge-plan').html button.data('short-description')
    $('#changePlan .new-recharge-plan-fee').html( '$' + button.data('recharge-fee-cents')/100.0 )
    $('#changePlan .new-recharge-plan-threshold').html button.data('recharge-threshold')
    $('#changePlan .new-recharge-plan-credits').html button.data('recharge-credits')
  )

app/views/users/_console.html.haml
.panel.panel-default
  .panel-heading
    Test Console
  .panel-body
    .console
      .row
        .col-sm-10.col-sm-offset-1
          = form_tag demo_result_path, class: 'form-horizontal', id: 'console' do
            .form-group
              = label_tag :street, "Delivery Line 1", class: 'col-sm-3'
              .col-sm-9
                = text_field_tag :street, params[:street], class: 'form-control input-sm'
            .form-group
              = label_tag :street2, "Delivery Line 2", class: 'col-sm-3'
              .col-sm-9
                = text_field_tag :street2, params[:street2], class: 'form-control input-sm'
            .form-group
              = label_tag :city, "City", class: 'col-sm-3'
              .col-sm-9
                = text_field_tag :city, params[:city], class: 'form-control input-sm'
            .form-group
              = label_tag :state, "State", class: 'col-sm-3'
              .col-sm-9
                = select_tag :state, options_for_select(State::ABBREVIATIONS), include_blank: true, class: 'form-control input-sm'
            .form-group
              = label_tag :zipcode, "ZIP Code", class: 'col-sm-3'
              .col-sm-9
                = text_field_tag :zipcode, params[:zipcode], class: 'form-control input-sm'

            .form-group
              .text-center
                = submit_tag 'Validate', class: 'btn btn-primary'
    
      .row
        .col-sm-12
          #results
            
:coffeescript
  $ ->
    hljs.initHighlightingOnLoad()
    $('form#console').on 'submit', (e)->
      $('#results').html('Querying...')
      e.preventDefault()
      data = {}
      $('form#console input,select').each( ()->
        data[$(this).attr('name')] = $(this).val()
      )
      $.ajax
        url: '#{demo_result_path(format: :json)}'
        authenticity_token: $('meta[name="csrf-token"]').attr('content')
        type: 'POST'
        data: data
        success: (data, textStatus, xhr)->
          console.log "Data: " + data
          if data.length == 0
            $('#results').html('No results found.')
          else          
            hasMap = data[0].metadata.latitude != 0
            result = HandlebarsTemplates['demo_results/create']({top: data[0], results: data, hasMap: hasMap})
            $('#results').html(result)
        error: (xhr, textStatus, errorThrown) ->
          $('#results').html('Unexpected error occurred.')
          console.log "Got an error " + textStatus + ", " + errorThrown

    $('#raw-result').on 'show.bs.modal', (e)->
      console.log('opening')
      clicked = $(e.relatedTarget)
      raw = clicked.data('raw')
      modal = $(this)
      modal.find('.modal-content #json-output').html(JSON.stringify(raw, null, 2))      

app/views/users/_curl_command.html.haml
#curl-command.modal.fade
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        cURL command
      .modal-body
        %pre
          %code.bash
            #curl-command
              :plain
                curl -H "X-SA-Auth-Id: <your ID> \
                     -H "X-SA-Auth-Token: <your Token> \
                     -H "Accept: application/json" \
                     -H "Content-type: application/json" \
                     -d '{"street":"STREET", "street2":"STREET2", "city":"CITY", "state":"STATE", "zipcode":"ZIPCODE"}' \
                     http://localhost:3000/address-query

app/views/users/_help.html.haml
.panel.panel-default
  .panel-heading
    Get Help
  .panel-body
    TODO

app/views/users/_overview.html.haml
.panel.panel-default
  .panel-heading
    Account Overview
  .panel-body
    .account-overview
      %fieldset
        %legend Usage
        .row
          .col-sm-5.credits-remaining
            .well
              Credits Remaining
              .count= number_with_delimiter(current_user.credits_remaining.value)
              .progress
                .progress-bar.progress-bar-danger{ style: 'width: 10%' }
                .progress-bar{ style: 'width: 60%' }
              .recharge              
                - if current_user.recharge_threshold.value
                  Auto-Recharges at <b>#{number_with_delimiter(current_user.recharge_threshold.value)}</b> credits
                .plan                 
                  = link_to "Change Recharge Plan", "#plan"
          .col-sm-7
            .text-center
              7-day Usage
            #chart-container{ style: 'width: 100%, height: 200px' }

      %fieldset
        %legend Authorization    
        .auth-id          
          .row
            .col-sm-12
              %b API Authorization ID
          .row      
            .col-sm-12.auth-id= current_user.id
        .auth-tokens        
          .row
            .col-sm-12
              %b API Authorization Tokens
              %table.tokens.table-condensed.table
                - current_user.auth_tokens.each do |token|
                  %tr
                    %td.token= token
                    %td.description
                      %i= token_description(current_user, token)
                    %td.delete
                      = link_to "Delete",
                        auth_token_path(token),
                        method: :delete,
                        class: 'btn btn-xs btn-danger',
                        data: {confirm: "Delete authorization token #{token} (#{token_description(current_user, token)})?"}
        .row
          .col-sm-12
            %button{ class: 'btn btn-sm btn-default', data: {toggle: "modal", target: "#addToken"}}
              = fa_icon 'plus'
              Add another authorization token
        
:coffeescript
  $ ->
    $('#chart-container').highcharts(
      chart:
        height: 150
        type: 'column'
      colors: ['#00B5B5','#F1654C']
      legend:
        enabled: false
      title:
        text: null
      xAxis:
        categories: #{@history.map(&:first)}
      yAxis:
        title:
          text: 'Requests'
      series: [{
          name: 'Requests'
          data: #{@history.map(&:last)}
        }]
    )

app/views/users/_plan.html.haml
- current_plan = current_user.plan
.panel.panel-default
  .panel-heading
    Recharge Plan
  .panel-body
    .plan
      - if current_user.has_payment_source?
        .row
          .col-sm-12
            Your current recharge plan is the <b>#{current_plan.short_description}</b> plan.
            It will automatically add <b>#{number_with_delimiter current_plan.recharge_credits}</b>
            credits to your account when your credit balance reaches <b>#{current_plan.recharge_threshold}</b>
            credits, and <b>$#{current_plan.recharge_fee} will be billed to your credit card</b>.
      - else
        .row
          .col-sm-12
            .alert.alert-warning
              Before you can sign up for an automatic recharge plan, you'll need to set up
              a credit card on your account. Head over to <a onclick="$('a.billing-link').trigger('click');">the Billing Tab</a>
              to do that first.
      .row
        .col-sm-12
          %table
            %tr
              - Plan.visible_to_users.order(:recharge_fee_cents).each do |plan|
                %td{ class: "#{plan == current_plan ? 'current' : 'not-current'}" }
                  .thumbnail
                    .caption
                      %h3= plan.short_description
                      %p= plan.description
                      .select
                        - if plan == current_user.plan
                          %b
                            = fa_icon 'check'
                            Your current plan
                        - else
                          - if current_user.has_payment_source?
                            %button.btn.btn-primary{ data: { toggle: 'modal', target: '#changePlan' }.merge(plan.attributes) }
                              Select
                          - else
                            &nbsp;
                            
      .row
        .col-sm-12
          %legend How Recharge Plans Work
          %p
            Payment for API usage is based on credits. Each API invocation costs
            one credit. When your account reaches its recharge threshold, it will
            automatically be "recharged" by billing your credit card for a new
            set of credits.
          %p
            The price of each individual credit varies based on how many credits
            you recharge at a time. The bigger the recharge, the bigger the discount!

= render partial: 'change_plan'            

app/views/users/_raw_result.html.haml
#raw-result.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        Raw JSON output
      .modal-body
        %pre
          %code
            #json-output

app/views/users/new.html.haml
%h1 New Account
  
= form_tag "/auth/identity/register" do
  - if @identity && @identity.errors.any?
    .alert.alert-danger
      %h2 #{pluralize(@identity.errors.count, "error")} prohibited this account from being saved:
      %ul
        - @identity.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = label_tag 'Name', :name
    = text_field_tag :name, @identity.try(:user).try(:name), class: 'form-control'
  .form-group    
    = label_tag 'E-mail address', :email
    = text_field_tag :email, @identity.try(:email), class: 'form-control'
  .form-group
    = label_tag :password
    = password_field_tag :password, nil, class: 'form-control'
  .form-group    
    = label_tag :password_confirmation
    = password_field_tag :password_confirmation, nil, class: 'form-control'
  .actions
    = submit_tag "Register", class: 'btn btn-primary'

app/views/users/show.html.haml
= render partial: 'shared/navbar'  
= render partial: 'shared/flash'      
      
.row
  .col-sm-3
    .tabpanel
      %ul.nav.nav-pills.nav-stacked#tabs
        %li.active= link_to 'Overview', '#overview', data: { toggle: 'tab' }
        %li= link_to 'Billing', '#billing', data: { toggle: 'tab' }, class: 'billing-link'
        %li= link_to 'Recharge Plan', '#plan', data: { toggle: 'tab' }
        %li= link_to 'Test console', '#console', data: { toggle: 'tab' }
        %li= link_to 'Get Help', '#help', data: { toggle: 'tab' }      
  .col-sm-9
    .tab-content
      #overview.tab-pane.active
        = render partial: "overview"
      #billing.tab-pane
        = render partial: "billing"
      #plan.tab-pane
        = render partial: "plan" 
      #console.tab-pane
        = render partial: "console"
      #help.tab-pane
        = render partial: "help"

= render 'add_token'
= render 'raw_result'
= render 'curl_command'

:coffeescript
  $ ->
    $('#tabs a').click (e)->
      e.preventDefault()
      $(this).tab('show')

    $("ul.nav-pills > li > a").on "shown.bs.tab", (e)->
      e.preventDefault()
      id = $(e.target).attr("href").substr(1)
      window.location.hash = '!' + id

    hash = '#' + window.location.hash.substr(2);
    $('#tabs a[href="' + hash + '"]').trigger 'click'

app/views/users/show.js.erb
$('tbody#payments').html('<%= escape_javascript render(@payments) %>');
$('#paginator').html('<%= escape_javascript(paginate(@payments, remote: true, theme: "bootstrap3").to_s) %>');