config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  match "/auth/:provider/callback" => "sessions#create", via: [:get, :post]
  match "/auth/failure", to: "sessions#failure", via: [:get, :post]
  match "/login", to: "sessions#new", :as => "login", via: [:get]
  match "/logout", to: "sessions#destroy", :as => "logout", via: [:get, :post]  #TODO
  match '/register', to: "users#new", :as => "register", via: [:get]
  resources :users do
    member do
      resource :payment_source
    end
  end
  resource  :password
  resource  :password_reset
  resources :auth_tokens
  resources :payments

  resource :demo_result
  resources :users

  post 'address-query' => 'street_address#query', :as => :query_street_address

  get 'health_check' => 'health_check#index', :as => :health_check
end

app/views/shared/_flash.html.haml
- if flash[:notice]
  .alert.alert-success.alert-dismissable.fade.in
    %button.close{ type: "button", data:{dismiss: "alert"}}
      = fa_icon 'times'
    = flash[:notice]
- if flash[:error]
  .alert.alert-danger.alert-dismissable.fade.in
    %button.close{ type: "button", data:{dismiss: "alert"}}
      = fa_icon 'times'    
    = flash[:error]

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{ type: "button", data: {toggle: "collapse", target: "#bs-example-navbar-collapse-1"} }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Sure Address", user_path(current_user), class: 'navbar-brand'

    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          %a{ href: "#", class: "dropdown-toggle", data: {toggle: "dropdown"}}
            = current_user.email
            %span.caret
          %ul.dropdown-menu
            %li
              = link_to "Change Password", edit_password_path
            %li
              = link_to "Sign out", logout_path