config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  match "/auth/:provider/callback" => "sessions#create", via: [:get, :post]
  match "/auth/failure", to: "sessions#failure", via: [:get, :post]
  match "/login", to: "sessions#new", :as => "login", via: [:get]
  match "/logout", to: "sessions#destroy", :as => "logout", via: [:get, :post]  #TODO
  match '/register', to: "users#new", :as => "register", via: [:get]
  resources :users do
    member do
      resource :payment_source
    end
  end
  resource  :password
  resource  :password_reset
  resources :auth_tokens
  resources :payments

  resource :demo_result
  resources :users

  post 'address-query' => 'street_address#query', :as => :query_street_address

  get 'health_check' => 'health_check#index', :as => :health_check
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'homepage'

  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
.hero
  %nav.navbar.navbar-default
    .container-fluid
      .navbar-header
        .navbar-brand
          = link_to "SureAddress", '/'
      .navbar-collapse        
        .navbar-right
          = link_to "Register", register_url, class: 'navbar-btn btn btn-info'
          = link_to "Sign in", login_url, class: 'navbar-link'
  
  %h1 Easy Address Verification
  %h2 Quickly check any address in the United States with <b>SureAddress</b>

  .demo
    = form_tag demo_result_path, class: 'form-inline', id: 'console' do
      = hidden_field_tag :street2
      .form-group
        = text_field_tag :street, params[:street], class: 'form-control input-lg', placeholder: 'Street Address'
      .form-group
        = text_field_tag :city, params[:city], class: 'form-control input-lg', placeholder: 'City'
      .form-group
        = select_tag :state, options_for_select(State::ABBREVIATIONS), prompt: 'State', class: 'form-control input-lg'
      .form-group
        = text_field_tag :zipcode, params[:zipcode], class: 'form-control input-lg', placeholder: 'ZIP Code'

      .form-group
        .text-center
          = submit_tag 'Try it out!', class: 'btn btn-info btn-lg'
    #results

.why
  .row
    .col-sm-8.col-sm-offset-2
      %h3
        = fa_icon 'arrow-right'
        Standardize
      %p
        Let Sure Address take care of formatting addresses
        = link_to "the way the USPS prefers.", "http://pe.usps.gov/text/pub28/welcome.htm"      
      %h3
        = fa_icon 'arrow-right'
        Validate
      %p
        = link_to "According to the United States Postal Service", "https://www.uspsoig.gov/sites/default/files/document-library-files/2014/ms-ar-14-006.pdf"
        over 6.8 billion pieces of mail (over 4.3%) were "undeliverable as addressed" in 2013.
        Don't let this be your mail to your customers!
      %h3
        = fa_icon 'arrow-right'
        Locate
      %p
        Most responses return the latitude and longitude of the queried address.

.try
  .row
    .col-sm-12
      %h3 Try it for free! No credit card required.
  .row
    .col-sm-12
      .cta.signup
        = link_to "Start using SureAddress now", new_user_path, class: 'btn btn-lg btn-info'

.footer
  .row
    .col-sm-12
      
:coffeescript
  $ ->
    $('form#console').on 'submit', (e)->
      $('#results').html('Querying...')
      e.preventDefault()
      data = {}
      $('form#console input,select').each( ()->
        data[$(this).attr('name')] = $(this).val()
      )
      $.ajax
        url: '#{demo_result_path(format: :json)}'
        authenticity_token: $('meta[name="csrf-token"]').attr('content')
        type: 'POST'
        data: data
        success: (data, textStatus, xhr)->
          console.log "Data: " + data
          if data.length == 0
            $('#results').html('No results found.')
          else          
            result = HandlebarsTemplates['homepage/create']({top: data[0], results: data})
            console.log "Result: " + result           
            $('#results').html(result)
        error: (xhr, textStatus, errorThrown) ->
          $('#results').html('Unexpected error occurred.')
          console.log "Got an error " + textStatus + ", " + errorThrown
        